account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile')
]

bike/urls.py
from django.urls import path
from . import views

app_name = 'bike'

urlpatterns = [
    path('bike-list', views.ListBikeView.as_view(), name='bike-list'),
    path('my-bike', views.MyBikesView.as_view(), name='my-bike')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('account/',include('account.urls',namespace="account")),
    path('bike/', include('bike.urls', namespace='bike')),
    path('reserve/', include('reservation.urls', namespace='reservation')),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request, 'home.html', context={

    })

home/templates/home.html
{% extends 'main.html' %}
{% block title %}{% endblock %}

{% block content %}
     <div class="mx-auto text-center">
        <img src="./../static/images/bidood.webp" class="block mx-auto my-10 rounded-lg">
        <p class="azar font-bold text-[1.3rem]">دوچرخه سواری هوشمند</p>
        <div class="flex gap-3 justify-center my-8 items-center">
            <a href="{% url 'account:login' %}" class="block border hover:bg-orange-500 hover:text-white duration-300 border-orange-500 text-orange-500 p-2 w-fit rounded-md azar">ورود به حساب</a>
            <a href="{% url 'account:signup' %}" class="block bg-orange-500 hover:bg-transparent hover:border hover:border-orange-500 hover:text-orange-500 duration-300 text-white p-2 w-fit rounded-md azar ">ثبت نام</a>
        </div>
    </div>
{% endblock %}