account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile')
]

bike/urls.py
from django.urls import path
from . import views

app_name = 'bike'

urlpatterns = [
    path('bike-list', views.ListBikeView.as_view(), name='bike-list'),
    path('my-bike', views.MyBikesView.as_view(), name='my-bike')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('account/',include('account.urls',namespace="account")),
    path('bike/', include('bike.urls', namespace='bike')),
    path('reserve/', include('reservation.urls', namespace='reservation')),
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    phone = models.CharField(max_length=11, default='0', null=True, verbose_name='شماره تماس')

    class Meta:
        verbose_name = "کاربر"
        verbose_name_plural = "کاربران"


    def __str__(self):
        return f"{self.first_name}{self.last_name}"

account/forms.py
from django import forms


class SignUpForm(forms.Form):
    first_name = forms.CharField(
        label='نام',
        widget=forms.TextInput()
    )
    last_name = forms.CharField(
        label='نام خانوادگی',
        widget=forms.TextInput()
    )
    email = forms.EmailField(
        label='ایمیل',
        widget=forms.EmailInput()
    )
    phone = forms.CharField(
        label='شماره تماس',
        widget=forms.TextInput()
    )
    password = forms.CharField(
        label="پسورد",
        widget=forms.TextInput()
    )
    confirm_password = forms.CharField(
        label="تکرار پسورد",
        widget=forms.TextInput()
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password == confirm_password:
            return confirm_password
        else:
            raise forms.ValidationError("رمز عبور های وارد شده یکسان نیستند")

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')

        if len(phone) > 11:
            raise forms.ValidationError("شماره تلفن معتبر نمیباشد")
        else:
            return phone


class LoginForm(forms.Form):
    email = forms.EmailField(
        label='ایمیل',
        widget=forms.EmailInput(),
        error_messages={
            'required': 'ایمیل خود را وارد کنید'
        }
    )
    password = forms.CharField(
        label='پسورد',
        widget=forms.TextInput(),
        error_messages={
            'required': 'پسورد خود را وارد کنید'
        }
    )

account/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import *
from .models import *


# Create your views here.
class SignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'signup.html', context={'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            exist_user: User & bool = User.objects.filter(email__iexact=form.cleaned_data.get('email')).exists()
            if not exist_user:
                new_user = User()
                new_user.first_name = form.cleaned_data.get('first_name')
                new_user.last_name = form.cleaned_data.get('last_name')
                new_user.email = form.cleaned_data.get('email')
                new_user.phone = form.cleaned_data.get('phone')
                new_user.set_password(form.cleaned_data.get('password'))
                new_user.username = form.cleaned_data.get('email')[0:5]
                new_user.is_staff = False
                new_user.is_superuser = False
                new_user.save()
                return redirect('account:login')
            else:
                form.add_error('email', 'این ایمیل از قبل ثبت نام شده است')
        else:
            form.add_error('confirm_password', 'خطایی در ثبت نام پیش آمده است')

        return render(request, 'signup.html', context={
            'form': form
        })


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', context={'form': form, })

    def post(self, request):
        form = LoginForm(request.POST)
        print(request.POST)
        if form.is_valid():
            user: User & bool = User.objects.filter(email__iexact=form.cleaned_data.get('email')).first()
            if user:
                is_password_correct = user.check_password(form.cleaned_data.get('password'))
                if is_password_correct:
                    login(request, user)
                    return redirect('account:profile')
                else:
                    form.add_error('password', 'رمزعبور وارد شده صحیح نمیباشد')
            else:
                form.add_error('email', 'ابتدا باید در سایت ثبت نام کنید')

        else:
            form.add_error('password', 'مشکلی در ثبت نام پیش آمده است')

        return render(request, 'login.html', context={'form': form})


@login_required(login_url="/account/login")
def logout_user(request):
    logout(request)
    return redirect("bike:bike-list")

@login_required(login_url="/account/login")
def profile(request):
    return render(request, 'profile.html', context={})

account/templates/login.html
{% extends 'main.html' %}
{% block title %}{% endblock %}

{% block content %}
    <h1 class="text-center azar font-bold my-4 text-[1.3rem]">
        ورود به حساب
    </h1>
    <section
            class="bg-white rounded-md shadow-xl w-fit gap-x-8 h-fit mx-auto mt-4 flex justify-around px-6"
    >
        <div>
            <form class="block p-4 mx-auto azar" method="post">
                {% csrf_token %}
                <div class="mt-8">
                    <label for="" class="block py-1 text-gray-600 mx-1 mb-2">ایمیل</label>
                    <input type="email" name="email" class="border border-orange-500 rounded-md p-2"/>
                    <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">
                        {{ form.email.errors }}
                    </p>
                </div>

                <div class="mt-4">
                    <label for="" class="block py-1 text-gray-600 mx-1 mb-2">رمزعبور</label>
                    <input type="password" name="password" class="border border-orange-500 rounded-md p-2"/>
                    <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">
                        {{ form.password.errors }}
                    </p>
                </div>

                <button type="submit" class="block mt-6 bg-orange-500 mx-auto text-white p-2 w-fit rounded-md azar">
                    ورود به حساب کاربری
                </button>
            </form>
            <span class="azar block my-2 text-orange-500 text-[0.9rem] text-center">حساب کاربری ندارید؟
                <a href="{% url 'account:signup' %}">ثبت نام</a></span>
        </div>
        <div class="text-center hidden md:block">
            <img src="./../static/images/bidood.webp" class="block mx-auto mt-14 rounded-lg"/>
            <p class="azar font-bold text-[1.3rem] my-4">
                دوچرخه سواری هوشمند
            </p>
        </div>
    </section>
{% endblock %}

account/templates/profile.html
{% extends 'main.html' %}
{% block title %}{% endblock %}

{% block content %}
    <h1 class="text-[2rem] azar font-bold text-orange-500 text-center mt-4 mb-8">حساب کاربری</h1>
    {% include 'menu.html' %}
    <section class="bg-white w-[25rem] pb-8 mx-auto rounded-md my-2">
        <h1 class="text-center azar py-4 text-[1.2rem]">اطلاعات کاربری</h1>
        <div class="flex flex-col gap-y-2">
            <p class="azar mx-6">نام:
                {% if request.user.first_name %}{{ request.user.first_name }}{% else %}ناشناس{% endif %}</p>
            <p class="azar mx-6">نام خانوادگی:
                {% if request.user.last_name %}{{ request.user.last_name }}{% else %}ناشناس{% endif %}</p>
            <p class="azar mx-6">ایمیل: {{ request.user.email }}</p>
            <p class="azar mx-6">شماره تماس: {{ request.user.phone }}</p>
        </div>
        <a href="{% url 'account:logout' %}"
           class="bg-red-400 block text-center mt-2 mx-6 text-white w-fit p-2 rounded-md azar flex items-center gap-x-2">
            خروج از حساب
        </a>
    </section>
{% endblock %}

account/templates/signup.html
{% extends 'main.html' %}
{% block title %}{% endblock %}

{% block content %}
    <h1 class="text-center azar font-bold my-4 text-[1.3rem]">ایجاد حساب کاربری</h1>
    <section class="bg-white rounded-md shadow-xl w-fit gap-x-8 h-fit mx-auto mt-4 flex justify-around px-6">
        <div>
            <form class="block p-4 mx-auto azar" method="post">
                {% csrf_token %}
                <div class="flex items-center gap-x-6">
                    <div class="mt-2 ">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">نام</label>
                        <input type="text" name="first_name" class="border border-orange-500 rounded-md p-2"
                               value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}">
                        <p class="text-[0.9rem] alert text-red-600 text-center mx-auto mt-1">{{ form.first_name.errors }}</p>
                    </div>

                    <div class="mt-2">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">نام خانوادگی</label>
                        <input type="text" name="last_name" class="border border-orange-500 rounded-md p-2"
                               value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}">
                        <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">{{ form.last_name.errors }}</p>
                    </div>
                </div>
                <div class="flex items-center gap-x-6">
                    <div class="my-2">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">شماره تماس</label>
                        <input type="text" name="phone" class="border border-orange-500 rounded-md p-2"
                               value="{% if form.phone.value %}{{ form.phone.value }}{% endif %}">
                        <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">{{ form.phone.errors }}</p>
                    </div>

                    <div class="my-2">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">ایمیل</label>
                        <input type="email" name="email" class="border border-orange-500 rounded-md p-2"
                               value="{% if form.email.value %}{{ form.default_renderer.value }}{% endif %}">
                        <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">{{ form.email.errors }}</p>
                    </div>
                </div>

                <div class="flex items-center gap-x-6">
                    <div class="my-2">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">رمزعبور</label>
                        <input type="password" name="password" class="border border-orange-500 rounded-md p-2">
                        <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">{{ form.password.errors }}</p>
                    </div>

                    <div class="my-2">
                        <label for="" class="block py-1 text-gray-600 mx-1 mb-2">تکرار رمزعبور</label>
                        <input type="password" name="confirm_password" class="border border-orange-500 rounded-md p-2">
                        <p class="text-[0.9rem] text-red-600 text-center mx-auto mt-1">{{ form.confirm_password.errors }}</p>
                    </div>
                </div>

                <button type="submit" class="block my-4 bg-orange-500 mx-auto text-white p-2 w-fit rounded-md azar ">ثبت
                    نام
                </button>
            </form>
        </div>
        <div class="text-center hidden md:block">
            <img src="./../static/images/bidood.webp" class="block mx-auto mt-14 rounded-lg">
            <p class="azar font-bold text-[1.3rem] my-4">دوچرخه سواری هوشمند</p>
        </div>
    </section>
{% endblock %}