bike/urls.py
from django.urls import path
from . import views

app_name = 'bike'

urlpatterns = [
    path('bike-list', views.ListBikeView.as_view(), name='bike-list'),
    path('my-bike', views.MyBikesView.as_view(), name='my-bike')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('account/',include('account.urls',namespace="account")),
    path('bike/', include('bike.urls', namespace='bike')),
    path('reserve/', include('reservation.urls', namespace='reservation')),
]

reservation/urls.py
from django.urls import path
from . import views
app_name = 'reservation'

urlpatterns = [
    path('get/<id>', views.get_bike, name='get-bike'),
    path('revert/<id>', views.revert_bike, name='revert-bike')
]

bike/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    type_name = models.CharField(max_length=250)
    type_slug = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'نوع'
        verbose_name_plural = 'دسته بندی'

    def __str__(self):
        return self.type_name

class Bike(models.Model):
    price = models.IntegerField(verbose_name='نرخ اجاره ساعتی')
    add_date = models.DateField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')
    status = models.BooleanField(default=False, verbose_name='اجاره داده شده')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, verbose_name='نوع')

    class Meta:
        verbose_name = "دوچرخه"
        verbose_name_plural = "دورچرخه ها"

    def __str__(self):
        return f"{self.id} - {'اجاره داده شده' if self.status else 'اجاره داده نشده'}"

bike/views.py
from django.shortcuts import render, redirect
from .models import *
from reservation.models import *
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ListBikeView(ListView):
    template_name = 'bike_list.html'
    context_object_name = 'bike'
    queryset = Bike.objects.all()
    ordering = ['status']

login_url = "/login/"
class MyBikesView(LoginRequiredMixin ,ListView):
    login_url = "/account/login"
    template_name = 'my_bike.html'
    queryset = BikeToUser.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bike"] = BikeToUser.objects.filter(user=self.request.user, status=True).all()
        return context

bike/templates/bike_list.html
{% extends 'main.html' %}
{% block title %}{% endblock %}

{% block content %}
    <h1 class="text-[2rem] azar font-bold text-orange-500 text-center mt-4 mb-8">ایستگاه دوچرخه</h1>
    {% include 'menu.html' %}
    <section class="flex justify-center flex-wrap gap-2">
        {% for item in bike %}
            <div class="flex bg-white rounded-md p-6 items-center azar shadow-md gap-x-8 mx-8">
                <div>
                    <img src="./../static/images/get-bike.png" alt=""
                         class="block w-[8rem] mb-8 border border-gray-100 rounded-md">
                </div>
                <div class="flex flex-col">
                <span class="my-1 flex items-center gap-x-2">
                    <i class="fas fa-tag text-gray-600"></i>
                     شناسه:  {{ item.id }}
                </span>
                    <span class="mt-2 flex items-center gap-x-2">
                     <i class="fas fa-money-bill-alt text-gray-600"></i>
                     هزینه(ساعتی):  {{ item.price }} تومان
                </span>
                    <span class="mt-2 flex items-center gap-x-2">
                 <i class="fas fa-plug text-gray-600"></i>
                    نوع: {{ item.type }}
            </span>

                    <span class="mt-2 flex items-center gap-x-2">
                <i class="fas fa-flag text-gray-600"></i>
                    وضعیت: {% if item.status == True %}اجاره داده شده{% else %}اجاره داده نشده{% endif %}</span>
                    {% if item.status == False %}
                        <a href="{% url 'reservation:get-bike' item.id %}"
                           class="mt-4 text-green-500 text-center rounded-md w-fit p-1 hover:text-white hover:bg-green-500 duration-300">اجاره
                            کردن</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

bike/templates/my_bike.html
{% extends 'main.html' %}
{% load jformat %}
{% block title %}{% endblock %}

{% block content %}
    <h1 class="text-[2rem] azar font-bold text-orange-500 text-center mt-4 mb-8">سفارشات من</h1>
    {% include 'menu.html' %}
    {% if messages %}
        {% for message in messages %}
            <p class="bg-red-400 text-white text-center mx-auto w-fit p-2 azar my-4 rounded-md">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <section class="flex justify-center flex-wrap gap-2">
        {% if bike %}
            {% for item in bike %}
                <div class="flex bg-white rounded-md p-6 w-fit items-center azar shadow-md gap-x-8 mx-8">
                    <div>
                        <img src="./../static/images/get-bike.png" alt=""
                             class="block w-[7rem] mb-2 border border-gray-100 rounded-md">
                    </div>
                    <div class="flex flex-col">
                        <span class="my-1">شناسه: {{ item.bike.id }}</span>
                        <span class="mt-2">هزینه اجاره: {{ item.bike.price }} تومان</span>
                        <span class="mt-2">تاریخ اجاره: {{ item.date | jformat:"%H:%M - %Y/%m/%d" }} </span>
                        <a href="{% url 'reservation:revert-bike' item.bike.id %}"
                           class="mt-4 text-red-500 text-center rounded-md w-fit p-1 hover:text-white hover:bg-red-500 duration-300">برگرداندن</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="azar text-[1.3rem] mt-12">شما هنوز هیچ دوچرخه ای اجاره نکرده اید!</p>
        {% endif %}
    </section>
{% endblock %}