account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile')
]

bike/urls.py
from django.urls import path
from . import views

app_name = 'bike'

urlpatterns = [
    path('bike-list', views.ListBikeView.as_view(), name='bike-list'),
    path('my-bike', views.MyBikesView.as_view(), name='my-bike')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path('account/',include('account.urls',namespace="account")),
    path('bike/', include('bike.urls', namespace='bike')),
    path('reserve/', include('reservation.urls', namespace='reservation')),
]

templates/main.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/style/tailwind.css"/>
    <link rel="stylesheet" href="/static/style/main.css"/>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
            integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
    />
</head>
<body class="bg-gray-100">
{% block content %}
{% endblock %}
</body>
</html>

templates/menu.html
{% extends 'main.html' %}
{% block content %}
    <div class="mx-auto flex justify-center text-center my-6 gap-x-6">
        <a href="{% url 'account:profile' %}" class="bg-green-500 text-white p-2 rounded-md azar flex items-center gap-x-2">
            <i class="fas fa-user"></i>
            <span>پروفایل</span>
        </a>
        <a href="{% url 'bike:my-bike' %}" class="bg-cyan-500 text-white p-2 rounded-md azar flex items-center gap-x-2">
             <i class="fas fa-list"></i>
            <span>سفارشات من</span>
        </a>
         <a href="{% url 'bike:bike-list' %}" class="bg-orange-500 text-white p-2 rounded-md azar flex items-center gap-x-2">
             <i class="fas fa-bicycle"></i>
            <span>ایستگاه دوچرخه</span>
        </a>
    </div>
{% endblock %}